"""Initial schema — all 13 core tables.

Revision ID: 0001_initial
Revises:
Create Date: 2026-01-01

This migration is intentionally generated by Base.metadata.create_all() at
runtime against the bound engine. We provide it as a single 'create-all' op
so first-time setup is one command:

    alembic upgrade head

For incremental schema changes after MVP, use `alembic revision --autogenerate`.
"""
from alembic import op
from sqlalchemy import inspect

from app.db.base import Base
import app.db.models  # noqa: F401

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
