"""add precipitation to atmospheric_observations

Revision ID: 2011aa816fd5
Revises: 232100135b83
Create Date: 2026-05-01 13:38:46.367345
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2011aa816fd5'
down_revision: Union[str, None] = '232100135b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atmospheric_observations', sa.Column('precipitation', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('atmospheric_observations', 'precipitation')
    # ### end Alembic commands ###
