"""add atmospheric observations

Revision ID: 232100135b83
Revises: 579f130d61e2
Create Date: 2026-04-30 11:34:17.334286
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '232100135b83'
down_revision: Union[str, None] = '579f130d61e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atmospheric_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cape', sa.Float(), nullable=True),
    sa.Column('lifted_index', sa.Float(), nullable=True),
    sa.Column('convective_inhibition', sa.Float(), nullable=True),
    sa.Column('temperature_2m', sa.Float(), nullable=True),
    sa.Column('dewpoint_2m', sa.Float(), nullable=True),
    sa.Column('relative_humidity_2m', sa.Float(), nullable=True),
    sa.Column('pressure_msl', sa.Float(), nullable=True),
    sa.Column('wind_speed_10m', sa.Float(), nullable=True),
    sa.Column('wind_direction_10m', sa.Float(), nullable=True),
    sa.Column('wind_speed_80m', sa.Float(), nullable=True),
    sa.Column('wind_direction_80m', sa.Float(), nullable=True),
    sa.Column('wind_speed_180m', sa.Float(), nullable=True),
    sa.Column('wind_direction_180m', sa.Float(), nullable=True),
    sa.Column('temperature_500hPa', sa.Float(), nullable=True),
    sa.Column('temperature_700hPa', sa.Float(), nullable=True),
    sa.Column('temperature_850hPa', sa.Float(), nullable=True),
    sa.Column('precipitable_water', sa.Float(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'observed_at', 'source', name='uq_atmos_loc_time_source')
    )
    op.create_index('ix_atmos_location_observed_at', 'atmospheric_observations', ['location_id', 'observed_at'], unique=False)
    op.create_index('ix_atmos_observed_at', 'atmospheric_observations', ['observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_atmos_observed_at', table_name='atmospheric_observations')
    op.drop_index('ix_atmos_location_observed_at', table_name='atmospheric_observations')
    op.drop_table('atmospheric_observations')
    # ### end Alembic commands ###
