"""add verification tables

Revision ID: 579f130d61e2
Revises: 0001_initial
Create Date: 2026-04-28 12:20:08.352675
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '579f130d61e2'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ground_truth_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=64), nullable=True),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_event_id', name='uq_gte_source')
    )
    op.create_index('ix_gte_event_at', 'ground_truth_events', ['event_at'], unique=False)
    op.create_index('ix_gte_event_type', 'ground_truth_events', ['event_type'], unique=False)
    op.create_index('ix_gte_lat_lng', 'ground_truth_events', ['latitude', 'longitude'], unique=False)
    op.create_table('verification_outcomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('calibrated_output_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('matched_event_id', sa.UUID(), nullable=True),
    sa.Column('predicted_probability', sa.Float(), nullable=False),
    sa.Column('tier_at_prediction', sa.String(length=16), nullable=True),
    sa.Column('decision_threshold', sa.Float(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('search_radius_km', sa.Float(), nullable=False),
    sa.Column('observed', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['calibrated_output_id'], ['calibrated_outputs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_event_id'], ['ground_truth_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calibrated_output_id', 'decision_threshold', name='uq_vo_pred_threshold')
    )
    op.create_index('ix_vo_location_id', 'verification_outcomes', ['location_id'], unique=False)
    op.create_index('ix_vo_outcome', 'verification_outcomes', ['outcome'], unique=False)
    op.create_index('ix_vo_window', 'verification_outcomes', ['window_start', 'window_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vo_window', table_name='verification_outcomes')
    op.drop_index('ix_vo_outcome', table_name='verification_outcomes')
    op.drop_index('ix_vo_location_id', table_name='verification_outcomes')
    op.drop_table('verification_outcomes')
    op.drop_index('ix_gte_lat_lng', table_name='ground_truth_events')
    op.drop_index('ix_gte_event_type', table_name='ground_truth_events')
    op.drop_index('ix_gte_event_at', table_name='ground_truth_events')
    op.drop_table('ground_truth_events')
    # ### end Alembic commands ###
